version: '3'
services:
    jira:
      image: hzwangmeng/jira
      links:
        - jira_sql
      ports:
        - "80:80"
    jira_sql:
      image: hzwangmeng/jira_sql
      ports:
          - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456