version: '3'
services:
    jira:
      image: hzwangmeng/jira:1.0
      links:
        - jira_sql
      ports:
        - "80:80"
    jira_sql:
      image: hzwangmeng/jira_sql:1.0
      ports:
          - "3309:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
